name: echoes
description: "Turn conversations into timeless family stories."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.2.3
  
  # State Management
  provider: ^6.1.2
  
  # Audio Recording & Playback
  flutter_sound: ^9.2.13
  flutter_tts: ^4.0.2
  
  # Backend & Storage
  supabase_flutter: ^2.5.6
  
  # HTTP & Networking
  dio: ^5.4.3+1
  
  # Image & Caching
  cached_network_image: ^3.3.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Audio Waveform UI
  audio_waveforms: ^1.0.5
  
  # Animations & UI
  lottie: ^3.1.2
  animations: ^2.0.11
  
  # Device Info
  device_info_plus: ^10.1.0
  
  # Path Provider
  path_provider: ^2.1.3
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # UUID Generation
  uuid: ^4.4.0
  
  # Google Fonts
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # Assets
  assets:
  - assets/images/
  - assets/animations/
  - assets/audio/
  - assets/onboarding/
